apiVersion: v1
kind: Service
metadata:
  name: gogs-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: gogs
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
    - name: ssh
      protocol: TCP
      port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.service.sshPort }}
  type: {{ .Values.service.type }}
